<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/ml_python.png' width=600/></center>

<img src = "https://github.com/Jangrae/img/blob/master/mobile2.png?raw=true" width=800 align="left"/>

# 실습 내용

- Random Search로 KNN 알고리즘 모델을 튜닝합니다.

# 1.환경 준비

- 기본 라이브러리와 대상 데이터를 가져와 이후 과정을 준비합니다.

In [36]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings(action='ignore')
%config InlineBackend.figure_format='retina'

In [37]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/jangrae/csv/master/mobile.csv'
data = pd.read_csv(path)

# 2.데이터 이해

- 분석할 데이터를 충분히 이해할 수 있도록 다양한 탐색 과정을 수행합니다.

In [38]:
# 상위 몇 개 행 확인
data.head()

id  COLLEGE  INCOME  OVERAGE  LEFTOVER   HOUSE  HANDSET_PRICE  \
0   1        0   31953        0         6  313378            161   
1   2        1   36147        0        13  800586            244   
2   3        1   27273      230         0  305049            201   
3   4        0  120070       38        33  788235            780   
4   5        1   29215      208        85  224784            241   

   OVER_15MINS_CALLS_PER_MONTH  AVERAGE_CALL_DURATION REPORTED_SATISFACTION  \
0                            0                      4                 unsat   
1                            0                      6                 unsat   
2                           16                     15                 unsat   
3                            3                      2                 unsat   
4                           21                      1            very_unsat   

  REPORTED_USAGE_LEVEL CONSIDERING_CHANGE_OF_PLAN  CHURN  
0               little                         no      0  
1               little                considering      0  
2          very_little                    perhaps      0  
3            very_high                considering      1  
4               little              never_thought      0

In [39]:
# 기술통계 확인
data.describe()

id       COLLEGE         INCOME       OVERAGE      LEFTOVER  \
count  20000.000000  20000.000000   20000.000000  20000.000000  20000.000000   
mean   10000.500000      0.502400   80281.447750     85.979550     23.898650   
std     5773.647028      0.500007   41680.586319     85.992324     26.816645   
min        1.000000      0.000000   20007.000000     -2.000000      0.000000   
25%     5000.750000      0.000000   42217.000000      0.000000      0.000000   
50%    10000.500000      1.000000   75366.500000     59.000000     14.000000   
75%    15000.250000      1.000000  115881.750000    179.000000     41.000000   
max    20000.000000      1.000000  159983.000000    335.000000     89.000000   

               HOUSE  HANDSET_PRICE  OVER_15MINS_CALLS_PER_MONTH  \
count   20000.000000   20000.000000                 20000.000000   
mean   493155.264250     389.615100                     8.000700   
std    252407.884692     213.820682                     8.925418   
min    150002.000000     130.000000                     0.000000   
25%    263714.250000     219.000000                     1.000000   
50%    452259.500000     326.000000                     4.000000   
75%    702378.000000     533.250000                    15.000000   
max    999996.000000     899.000000                    29.000000   

       AVERAGE_CALL_DURATION         CHURN  
count           20000.000000  20000.000000  
mean                6.002250      0.492600  
std                 4.402558      0.499958  
min                 1.000000      0.000000  
25%                 2.000000      0.000000  
50%                 5.000000      0.000000  
75%                10.000000      1.000000  
max                15.000000      1.000000

# 3.데이터 준비

- 전처리 과정을 통해 머신러닝 알고리즘에 사용할 수 있는 형태의 데이터를 준비합니다.

**1) 변수 제거**

In [40]:
# 제거 대상: id
drop_cols = ['id']

# 변수 제거
data.drop(drop_cols, axis=1, inplace=True)

# 확인
data.head()

COLLEGE  INCOME  OVERAGE  LEFTOVER   HOUSE  HANDSET_PRICE  \
0        0   31953        0         6  313378            161   
1        1   36147        0        13  800586            244   
2        1   27273      230         0  305049            201   
3        0  120070       38        33  788235            780   
4        1   29215      208        85  224784            241   

   OVER_15MINS_CALLS_PER_MONTH  AVERAGE_CALL_DURATION REPORTED_SATISFACTION  \
0                            0                      4                 unsat   
1                            0                      6                 unsat   
2                           16                     15                 unsat   
3                            3                      2                 unsat   
4                           21                      1            very_unsat   

  REPORTED_USAGE_LEVEL CONSIDERING_CHANGE_OF_PLAN  CHURN  
0               little                         no      0  
1               little                considering      0  
2          very_little                    perhaps      0  
3            very_high                considering      1  
4               little              never_thought      0

**2) x, y 분리**

In [41]:
# Target 설정
target = 'CHURN'

# 데이터 분리
x = data.drop(target,axis=1)
y = data.loc[:,target]

**3) 가변수화**

In [42]:
# 가변수화 대상: REPORTED_SATISFACTION, REPORTED_USAGE_LEVEL, CONSIDERING_CHANGE_OF_PLAN
dum_cols = ['REPORTED_SATISFACTION', 'REPORTED_USAGE_LEVEL', 'CONSIDERING_CHANGE_OF_PLAN']

# 가변수화
x = pd.get_dummies(x, columns=dum_cols, drop_first=True, dtype=int)

# 확인
x.head()

COLLEGE  INCOME  OVERAGE  LEFTOVER   HOUSE  HANDSET_PRICE  \
0        0   31953        0         6  313378            161   
1        1   36147        0        13  800586            244   
2        1   27273      230         0  305049            201   
3        0  120070       38        33  788235            780   
4        1   29215      208        85  224784            241   

   OVER_15MINS_CALLS_PER_MONTH  AVERAGE_CALL_DURATION  \
0                            0                      4   
1                            0                      6   
2                           16                     15   
3                            3                      2   
4                           21                      1   

   REPORTED_SATISFACTION_sat  REPORTED_SATISFACTION_unsat  \
0                          0                            1   
1                          0                            1   
2                          0                            1   
3                          0                            1   
4                          0                            0   

   REPORTED_SATISFACTION_very_sat  REPORTED_SATISFACTION_very_unsat  \
0                               0                                 0   
1                               0                                 0   
2                               0                                 0   
3                               0                                 0   
4                               0                                 1   

   REPORTED_USAGE_LEVEL_high  REPORTED_USAGE_LEVEL_little  \
0                          0                            1   
1                          0                            1   
2                          0                            0   
3                          0                            0   
4                          0                            1   

   REPORTED_USAGE_LEVEL_very_high  REPORTED_USAGE_LEVEL_very_little  \
0                               0                                 0   
1                               0                                 0   
2                               0                                 1   
3                               1                                 0   
4                               0                                 0   

   CONSIDERING_CHANGE_OF_PLAN_considering  \
0                                       0   
1                                       1   
2                                       0   
3                                       1   
4                                       0   

   CONSIDERING_CHANGE_OF_PLAN_never_thought  CONSIDERING_CHANGE_OF_PLAN_no  \
0                                         0                              1   
1                                         0                              0   
2                                         0                              0   
3                                         0                              0   
4                                         1                              0   

   CONSIDERING_CHANGE_OF_PLAN_perhaps  
0                                   0  
1                                   0  
2                                   1  
3                                   0  
4                                   0

**4) 학습용, 평가용 데이터 분리**

In [43]:
# 모듈 불러오기
from sklearn.model_selection import train_test_split

# 7:3으로 분리
x_train, x_test, y_train, y_test = train_test_split(x, y ,test_size=.3, random_state=1)

**5) 정규화**

In [44]:
# 모듈 불러오기
from sklearn.preprocessing import MinMaxScaler

# 정규화
scaler = MinMaxScaler()
scaler.fit(x_train)
x_train_s = scaler.transform(x_train)
x_test_s = scaler.transform(x_test)

# 4.성능 예측

- k-Fold Cross Validation을 사용해 모델의 성능을 예측합니다.

In [45]:
# 불러오기
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix

In [46]:
# 선언하기
model_knn = KNeighborsClassifier()

In [47]:
# 성능예측
cv_score = cross_val_score(model_knn, x_train_s, y_train, cv=5)

In [48]:
# 결과확인
print(cv_score)
print('평균: ',cv_score.mean())

# 성능 저장
result = {}
result['KNN'] = cv_score.mean()

[0.58571429 0.60035714 0.57785714 0.60321429 0.59785714]
평균:  0.5930000000000001


# 5.모델 튜닝


- Random Search로 튜닝을 진행합니다.

**1) 모델 튜닝**

In [49]:
# 파라미터 선언
  # n_neighbors: range(3, 21)
params = {'n_neighbors' : range(3,21)}

# Random Search 선언
  # cv=5
  # n_iter=10
  # scoring='accuracy'
model = RandomizedSearchCV(model_knn,           # 기본 모델 이름
                           params,              # 앞에서 선언한 튜닝용 파라미터 변수
                           cv=5,                # k-fold Cross Validation(default=5)
                           n_iter=10,           # Random하게 시도할 횟수(default=10)
                           scoring='accuracy')  # 평가 방법

In [56]:
# 학습하기
model.fit(x_train_s, y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(),
                   param_distributions={'n_neighbors': range(3, 21)},
                   scoring='accuracy')

**2) 결과 확인**

In [57]:
# mean_test_score 확인
model.cv_results_['mean_test_score']

array([0.59578571, 0.5905    , 0.59835714, 0.59535714, 0.59542857,
       0.593     , 0.59314286, 0.59885714, 0.59507143, 0.59714286])

In [58]:
# 최적 파라미터
model.best_params_

{'n_neighbors': 19}

In [59]:
# 최고 성능
model.best_score_

0.5988571428571429

# 6. 성능 평가

- 학습을 통해 예상한 성능과 실제 평가에 따른 성능은 차이가 있을 수 있습니다.
- 예선전에서 성적이 좋았다고 본선에서도 성적이 좋다고 보장할 수는 없겠지요?

In [60]:
# 예측하기
y_pred = model.predict(x_test_s)

In [61]:
# 평가하기
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[2039 1026]
 [1253 1682]]
              precision    recall  f1-score   support

           0       0.62      0.67      0.64      3065
           1       0.62      0.57      0.60      2935

    accuracy                           0.62      6000
   macro avg       0.62      0.62      0.62      6000
weighted avg       0.62      0.62      0.62      6000

